name: R elease

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - platform: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{matrix.platform}}  # 使用 Windows 环境进行构建

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用的 Node.js 版本

      # 安装 Tauri CLI 及依赖
      - name: Install Tauri CLI and dependencies
        run: |
          npm install -g @tauri-apps/cli  # 安装 Tauri CLI
          npm install                   # 安装项目依赖

      # 安装 Rust 和相关工具链
      # - name: Set up Rust
      #   uses: actions/setup-rust@v1
      #   with:
      #     rust-version: '1.60.0'  # 使用的 Rust 版本
      - name: Install Rust
        run: |
          rustup target add ${{matrix.target}}

      # 安装 Windows 依赖（如 Visual Studio 编译工具）
      - name: Install Windows Build Dependencies
        run: |
          choco install visualstudio2019buildtools
          choco install windows-sdk-10.1

      # 使用 Tauri 构建应用
      - name: Build Tauri App
        run: |
          tauri build

      # 上传构建的可执行文件作为 Artifact（可选）
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tauri-windows-build
          path: target/release/bundle/installer/*.exe  # 你要上传的构建文件路径
